codenvy/onpremises

onpremises-ide-packaging-tomcat-api/src/assembly/assembly.xml, onpremises-ide-packaging-tomcat-codenvy-allinone/pom.xml, onpremises-ide-packaging-tomcat-codenvy-allinone/src/assembly/assembly.xml, onpremises-ide-packaging-war-factory/pom.xml, onpremises-ide-packaging-war-factory/src/assembly/assembly.xml, pom.xml
We need to re-pack factory war with odyssey resources specified from odyssey.classifier variable
@skabashnyuk  @sleshchenko please review
=> CDEC-462: Add custom packaging-war-factory

onpremises-ide-packaging-tomcat-site/pom.xml, onpremises-ide-packaging-tomcat-site/src/assembly/assembly.xml, onpremises-ide-packaging-war-next-ide-codenvy/pom.xml, onpremises-ide-packaging-war-next-ide-codenvy/src/assembly/assembly.xml, pom.xml
Need to create custom war-next-ide-codenvy to change IDE.jsp in it.
@skabashnyuk  please review
=> CDEC-474: Add custom war-next-ide-codenvy

onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
=> IDEX-2726: move start of ws agent to che-core

onpremises-ide-packaging-war-platform-api/pom.xml, onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java, onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiServletModule.java
=> IDEX-3920 Add dependencies and bindings for SSH API

onpremises-ide-packaging-war-platform-api/pom.xml
=> IDEX-4010 Add dependency to machine-ext-server

onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
@skabashnyuk Please review my changes
=> CDEC-501 Bind value for auth.no.account.found.page property

onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
=> CDEC-503 Exclude requests to /api/user/settings from login filtering

onpremises-ide-packaging-tomcat-ext-server/pom.xml, onpremises-ide-packaging-tomcat-ext-server/src/assembly/assembly.xml, onpremises-ide-packaging-tomcat-ext-server/src/assembly/server.xml, onpremises-ide-packaging-war-ext-server/pom.xml, onpremises-ide-packaging-war-ext-server/src/main/java/com/codenvy/ext/java/server/ApiEndpointProvider.java, onpremises-ide-packaging-war-ext-server/src/main/java/com/codenvy/ext/java/server/EventBusURLProvider.java, onpremises-ide-packaging-war-ext-server/src/main/java/com/codenvy/ext/java/server/MachineModule.java, onpremises-ide-packaging-war-ext-server/src/main/java/com/codenvy/ext/java/server/MachineServletModule.java, onpremises-ide-packaging-war-ext-server/src/main/java/com/codenvy/ext/java/server/UserTokenProvider.java, onpremises-ide-packaging-war-ext-server/src/main/webapp/WEB-INF/classes/codenvy/che-machine-configuration.properties, onpremises-ide-packaging-war-ext-server/src/main/webapp/WEB-INF/web.xml, pom.xml
updating onpremises-ide-packaging-war-ext-server based on cloud-ide-packaging-war-ext-server
=> CLDIDE-2672 create onpremises-ide-packaging-war-ext-server module

onpremises-ide-packaging-tomcat-ext-server/pom.xml
depends on https://github.com/codenvy/codenvy-depmgt/pull/27
@skabashnyuk @vparfonov
=> CDEC-491 fixing onpremises-ide-packaging-tomcat-ext-server dependency

onpremises-ide-packaging-war-ext-server/pom.xml, onpremises-ide-packaging-war-ext-server/src/main/java/com/codenvy/ext/java/server/MachineServletModule.java
Allow cross domain requests to workspace agent.
@skabashnyuk, @vinokurig please review
=> IDEX-4091: Add CORS filter

onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiServletModule.java
Change-Id: I79f190d8e7d0688c19d12d61217d66d5d6d43009
Signed-off-by: Florent BENOIT <fbenoit@codenvy.com>
=> IDEX-4293 enable CORS on workspace master allowing to import remote workspaces

onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
=> CLDIDE-2692: Bind limiting implementations

onpremises-ide-packaging-war-platform-api/pom.xml
Change-Id: I150fa859143da61775a06e0d5d5a1c7a6151f9e2
Signed-off-by: Florent BENOIT <fbenoit@codenvy.com>
=> Fix the order of artifacts in the pom.xml

onpremises-ide-packaging-war-platform-api/pom.xml
Signed-off-by: Sergii Kabashniuk <skabashnyuk@codenvy.com>
=> Remove deprecated modules

onpremises-ide-packaging-war-ext-server/pom.xml, onpremises-ide-packaging-war-ext-server/src/main/java/com/codenvy/ext/java/server/MachineModule.java, onpremises-ide-packaging-war-ext-server/src/main/java/com/codenvy/ext/java/server/MachineServletModule.java, onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
=> Add swagger module on ws-master and ws-agent

onpremises-ide-packaging-war-platform-api/pom.xml
@skabashnyuk @riuvshin please review
=> CODENVY-47: Send Codenvy logo as attachmant in emails

onpremises-ide-packaging-war-ext-server/pom.xml, onpremises-ide-packaging-war-platform-api/pom.xml, onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java, onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiServletModule.java
Signed-off-by: Mihail Kuznyetsov <mkuznyetsov@codenvy.com>
=> Enable BitBucker OAuth 2.0

onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
=> IDEX-4222: fix code after changes in the model of workspace

onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
=> Revert "Revert "IDEX-4222: fix code after changes in the model of workspace""

onpremises-ide-packaging-war-ext-server/pom.xml
=> CODENVY-103: add project type dependency

onpremises-ide-packaging-war-platform-api/pom.xml
=> adding codenvy-plugin-github dependency

onpremises-ide-packaging-war-platform-api/src/main/webapp/WEB-INF/classes/codenvy/codenvy-api-configuration.properties
@eivantsov @garagatyi @skabashnyuk
=> fix props according to changes in CHE

onpremises-ide-packaging-war-ext-server/src/main/java/com/codenvy/ext/java/server/MachineModule.java, onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
@skabashnyuk Can you review my changes?
=> Rename CodenvyAsynchronousJobPool to CheAsynchronousJobPool

upload.sh
=> INFRA-949: change puppet master dns to new one
